### ISSUE TITLE
[feature request] Can you make it export files and file addresses in base 10 rather than hexadecimal?

### ISSUE THREAD

**Issue by hobohyperborian** [queueRAM/ogre_battle_tools#2]
I'm working on a OB 64 POLC modding tools project, and navigating the directories is a nightmare due to how Windows sorts files and folders. It would be very handy to have the directories and files be in base 10.

Also how did you do the "drag file to program and it works automatically" thing?

**Comment by queueRAM** [comment]
> navigating the directories is a nightmare due to how Windows sorts files and folders

It would be better to fix how your OS sorts files in directories. For Windows, you can change the sort order using the `NoStrCmpLogical` registry key. See more details on https://superuser.com/questions/1802675/sorting-files-and-folders-by-hexadecimal-and-decimal-values

> Also how did you do the "drag file to program and it works automatically" thing?

Sorry, I don't quite follow. What is this in reference to?

**Comment by hobohyperborian** [comment]
> Sorry, I don't quite follow. What is this in reference to?
The directions I am following state that that I should left-click and drag the OB64 ROM to ogre_battle_tools-master.exe. After I do this, a cmd.exe window appears with a progress report on files decompressed and extracted to their specific directories.

I assume this is a new feature of Windows, a way to run a normally command line program in the current working directory without actually using the command line?

Also while I have your attention, I am building a tool to edit the rom and whenever someone edits the shop pointer table and shop data, the file is too large. When this person goes to the test the modded shop, they get an "Unknown memory action Emulation stopped" error in Project 64.

I assume that there is a pointer table somewhere that stores the addresses of all compressed files, and this isn't updated when  compressed files with new or perhaps just larger file sizes are inserted back into the game. Do you know anything about this, specifically if such a data structure exists and how to update it with new filesizes and file locations should they change?

Here are the instructions we are using:

```
Editing compressed files in Ogre Battle 64

Step 1. Extract Ogre Battle Tools by queueRAM.zip to directory.

Step 2. Copy rom to same directory.

Step 3. Drag ogre battle rom to ogre_battle_tools-master.exe. Files will be extracted to ogre_dump folder.

Step 4. Open ogre_dump and navigate to the file you wish to edit. Ie. Enemydat.bin is in subdirectory 0274 29D8.

Step 5. Copy file to same directory as lha.exe and armips.exe.

Step 6. Open file in hex editor and make desired changes.

Step 7. Open command prompt and navigate to the folder containing lha.exe and armips.exe.

Step 8. Run lha c XXXXXXXX.lha XXXXXXXX.bin to create new .lha file with modified data.

Ie. lha c 027429D8.lha enemydat.bin to create a new lha file containing the formation data.

Step 9. Check XXXXXXXX.lha size in bytes and record the number.

Step 10. Edit ogre_test.asm in a text editor with the file information you’ve edited and the size recorded in step 9. See attached picture for example of 027429D8.lha.

Step 11. Run armips ogre_test.asm from command prompt. New rom file will be created with modified file.
```

I'm also considering finding - or God help me writing - compression code that is more effective at compression than whatever we have.
